language: objective-c
osx_image: xcode7.2
# Ugly workarounds to compile on OSX/64bits... where SwiftyGPIO will never run... 
before_script:
  - sed -i ""  s/let\ thread\ =\ NSThread\(\){// Sources/SwiftyGPIO.swift 
  - sed -i ""  s/}\ \/\/NSThread// Sources/SwiftyGPIO.swift 
  - sed -i ""  s/thread.start\(\)// Sources/SwiftyGPIO.swift 
  - sed -i ""  s/return\ thread/return\ NSThread\(\)/ Sources/SwiftyGPIO.swift 
  - sed -i ""  s/GPIO_BASE:Int/GPIO_BASE:Int64/ Sources/SwiftyGPIO.swift
  - echo "let O_SYNC:Int32=1052672" > Sources/main.swift
script: files=$(find Sources -regex '.*[^/]swift') && xcrun -sdk macosx swiftc $files
